<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1.0.-Pandas---Первое-знакомство" data-toc-modified-id="1.0.-Pandas---Первое-знакомство-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>1.0. Pandas - Первое знакомство</a></span></li><li><span><a href="#НО" data-toc-modified-id="НО-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>НО</a></span></li><li><span><a href="#1.1.-Pandas-DataFrame" data-toc-modified-id="1.1.-Pandas-DataFrame-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>1.1. Pandas DataFrame</a></span></li><li><span><a href="#1.2.-Индексирование." data-toc-modified-id="1.2.-Индексирование.-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>1.2. Индексирование.</a></span></li><li><span><a href="#1.3.-Работа-со-столбцами." data-toc-modified-id="1.3.-Работа-со-столбцами.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>1.3. Работа со столбцами.</a></span></li><li><span><a href="#1.4.-File-I/O." data-toc-modified-id="1.4.-File-I/O.-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>1.4. File I/O.</a></span></li></ul></div>

# 1.0. Pandas - Первое знакомство

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np

http://pandas.pydata.org/

Pandas - open-source  проект, предоставляющий средства для работы с данными в Питоне с использованием абстракций более высокого уровня, чем numpy.

В основе своей pandas полагается на структуры данных numpy, но вместе с тем предоставляет:

* различные типы данных в рамках одной структуры pandas.DataFrame;
* работу с пропущенными значениями;
* удобную работу с типом DateTime;
* набор методов для совместного использования нескольких массивов данных.

** Series **

Series - это массив размерности один, который может содержать данные различного типа, и 1:1 соответствие между данными и некоторой меткой, присвоенной каждому элементу.

In [3]:
series = pd.Series([-12, np.NAN, 1])

In [4]:
series

0   -12.0
1     NaN
2     1.0
dtype: float64

In [5]:
series.values

array([-12.,  nan,   1.])

In [6]:
series.index

RangeIndex(start=0, stop=3, step=1)

In [7]:
series

0   -12.0
1     NaN
2     1.0
dtype: float64

Мы можем создавать объекты, самостоятельно задавая индекс:

In [8]:
series2 = pd.Series([0, 1, 2], index=['a', 'b', 'c'], name='column')

In [9]:
series2.name

'column'

In [10]:
series2

a    0
b    1
c    2
Name: column, dtype: int64

Преимущества индексирования понятны - мы имеем быстрый доступ к элементам массива, при этом можем пользоваться всеми (практически) свойствами массивов numpy.

In [11]:
series[0]

-12.0

In [12]:
series2["a"]

0

In [13]:
series[0:2]

0   -12.0
1     NaN
dtype: float64

**Булево индексирование:**

In [14]:
series > 0

0    False
1    False
2     True
dtype: bool

In [15]:
series.values > 0

array([False, False,  True])

In [16]:
series[series > 0]

2    1.0
dtype: float64

In [17]:
0 in series

True

In [18]:
series

0   -12.0
1     NaN
2     1.0
dtype: float64

Конструктор принимет массив ранга один либо словарь. Ключи словаря используются как индекс (в отсортированном порядке):

In [19]:
pd.Series({'a': 1, 'c': 2, 'b': 3})

a    1
c    2
b    3
dtype: int64

In [20]:
pd.Series({'a': 1, 'c': 2, 'c': 10, 'b': 3})

a     1
c    10
b     3
dtype: int64

In [21]:
index = ['a_letter', 'b_letter', 'c_letter']

Если вызывается конструктор со словарем и парметром index = , то отсутствующие в словаре ключи получат NaN.

In [22]:
pd.Series({'a_letter': 1, 'b_letter': 2, 'c': 3}, index=index)

a_letter    1.0
b_letter    2.0
c_letter    NaN
dtype: float64

In [23]:
pd.Series([1, 2, 3], index=index)

a_letter    1
b_letter    2
c_letter    3
dtype: int64

Операции с Series напоминают операции с ndarray:

In [24]:
series

0   -12.0
1     NaN
2     1.0
dtype: float64

In [25]:
series[1] = 100

In [26]:
series

0    -12.0
1    100.0
2      1.0
dtype: float64

In [27]:
series + series

0    -24.0
1    200.0
2      2.0
dtype: float64

In [28]:
series * series

0      144.0
1    10000.0
2        1.0
dtype: float64

In [29]:
np.exp(series.astype(int))

0    6.144212e-06
1    2.688117e+43
2    2.718282e+00
dtype: float64

Самому Series и индексу можно присвоить атрибут имя:

In [30]:
series.name = 'some_test_series'

In [31]:
series

0    -12.0
1    100.0
2      1.0
Name: some_test_series, dtype: float64

In [32]:
series.index.name = 'some_test_index'

In [33]:
series

some_test_index
0    -12.0
1    100.0
2      1.0
Name: some_test_series, dtype: float64

In [34]:
series.index

RangeIndex(start=0, stop=3, step=1, name='some_test_index')

Важно помнить, как pandas обращается с несовпадающими индексами:

In [35]:
first_series = pd.Series({'a': 1, 'b': 2, 'c': 2})
second_series = pd.Series({'a': 1, 'b': 2, 'd': -1})

In [36]:
first_series + second_series

a    2.0
b    4.0
c    NaN
d    NaN
dtype: float64

In [37]:
first_series + second_series

a    2.0
b    4.0
c    NaN
d    NaN
dtype: float64

Индекс всегда можно поменять:

In [38]:
series

some_test_index
0    -12.0
1    100.0
2      1.0
Name: some_test_series, dtype: float64

In [39]:
series.index = ['a_letter', 'b_letter', 'c_letter']

In [40]:
series

a_letter    -12.0
b_letter    100.0
c_letter      1.0
Name: some_test_series, dtype: float64

In [41]:
series.loc['a_letter':"b_letter"]

a_letter    -12.0
b_letter    100.0
Name: some_test_series, dtype: float64

In [42]:
series.a_letter

-12.0

In [43]:
series.iloc[0:2]

a_letter    -12.0
b_letter    100.0
Name: some_test_series, dtype: float64

In [44]:
series[0:2]

a_letter    -12.0
b_letter    100.0
Name: some_test_series, dtype: float64

In [45]:
series['a_letter'] = 200

In [46]:
series

a_letter    200.0
b_letter    100.0
c_letter      1.0
Name: some_test_series, dtype: float64

# 1.1. Pandas DataFrame

Представим себе структуру, которая могла бы содержать несколько объекто типа Series, объединенных общим индексом. Тогда бы такая структура являлась pandas.DataFrame - табличным форматом данных, снабженным 2 типами индексов - строчным и колоночным.

In [47]:
df = pd.DataFrame({'A': [20, 10, 30], 'B': np.random.randn(3),
                   'C': ['A', 'B', 'C']}, index=['a', 'b', 'c'])

In [48]:
df

A         B  C
a  20  0.459116  A
b  10 -0.342634  B
c  30  0.011614  C

Выбор столбца ничем не отличается от стандартного \_\_getitem\_\_ синтаксиса:

In [49]:
df['A']

a    20
b    10
c    30
Name: A, dtype: int64

In [50]:
df[['A', 'C']]

A  C
a  20  A
b  10  B
c  30  C

In [51]:
df.A.values

array([20, 10, 30])

Возможные аргументы для конструктора:

* массив ранга 2 (индексы для столбцов и строк передаются отдельным аргументом либо будет использован xrange);
* словарь массивов ранга 1 (ключ - имя стобца, данные - элементы последовательности);
* словарь объектов pd.Series;
* словарь словарей (ключи внутреннего словаря - имена столбцов), ключи внешнего словаря - индекс обеъкта;

Выбор строки:

In [52]:
df.loc[['a', 'b']]

A         B  C
a  20  0.459116  A
b  10 -0.342634  B

--  N: Обратите внимание - slice подобного типа включает в себя крайний объект "справа".

In [53]:
df.iloc[0:2]

A         B  C
a  20  0.459116  A
b  10 -0.342634  B

--  N: А такой - не включает.

In [54]:
df.loc['a':'b']

A         B  C
a  20  0.459116  A
b  10 -0.342634  B

In [55]:
df.loc['a':'b', ['A', 'C']]

A  C
a  20  A
b  10  B

In [56]:
df.iloc[0:2, [0, 2]]

A  C
a  20  A
b  10  B

** Операции с dataframe **

In [57]:
df

A         B  C
a  20  0.459116  A
b  10 -0.342634  B
c  30  0.011614  C

In [58]:
df[['A', 'B']] + 5

A         B
a  25  5.459116
b  15  4.657366
c  35  5.011614

In [59]:
df[['A', 'C']] + df[['A', 'C']]

A   C
a  40  AA
b  20  BB
c  60  CC

Теперь внимание:

In [60]:
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [6, 2, 4], 'B': [9, 1, 4]}, index=[2, 0, 1])

In [61]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [62]:
df2

A  B
2  6  9
0  2  1
1  4  4

In [63]:
df1 + df2

A   B
0  3   5
1  6   9
2  9  15

In [64]:
df1.values

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
df2.values

array([[6, 9],
       [2, 1],
       [4, 4]])

In [66]:
df1.values + df2.values

array([[ 7, 13],
       [ 4,  6],
       [ 7, 10]])

Очень хорошо!

In [67]:
df3 = pd.DataFrame(np.random.randn(5, 3), columns=['A', 'B', 'C'])
df3

A         B         C
0 -0.449083  0.098019 -2.656571
1 -1.654008  0.557089  1.520829
2 -0.313241 -0.450316  0.418996
3  0.573049  0.890331 -0.679188
4  0.635671  0.609737 -0.453606

In [68]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [69]:
df1 + df3

A         B   C
0  0.550917  4.098019 NaN
1  0.345992  5.557089 NaN
2  2.686759  5.549684 NaN
3       NaN       NaN NaN
4       NaN       NaN NaN

После примера с Series - такое поведение как раз и ожидалось.

Тем не менее, бывают случаи, когда нам требуется чем - либо заполнить места, в которых индекс не пересекается. В таких случаях удобно использовать параметр fill_value.

In [70]:
df1.add(df3, fill_value=0)

A         B         C
0  0.550917  4.098019 -2.656571
1  0.345992  5.557089  1.520829
2  2.686759  5.549684  0.418996
3  0.573049  0.890331 -0.679188
4  0.635671  0.609737 -0.453606

Таких "гибких" арифметических операций 4:

* df.add;
* df.sub;
* df.div;
* df.mul.

Как наследие массива из numpy, мы можем использовать broadcasting:

In [71]:
df = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['U', 'O', 'T', 'Z'])

In [72]:
df

b     d     e
U  0.0   1.0   2.0
O  3.0   4.0   5.0
T  6.0   7.0   8.0
Z  9.0  10.0  11.0

In [73]:
series = df.iloc[0]

In [74]:
series

b    0.0
d    1.0
e    2.0
Name: U, dtype: float64

In [75]:
df

b     d     e
U  0.0   1.0   2.0
O  3.0   4.0   5.0
T  6.0   7.0   8.0
Z  9.0  10.0  11.0

In [76]:
series

b    0.0
d    1.0
e    2.0
Name: U, dtype: float64

In [77]:
df - series

b    d    e
U  0.0  0.0  0.0
O  3.0  3.0  3.0
T  6.0  6.0  6.0
Z  9.0  9.0  9.0

Совпадение считается по индексу. Если индексы не совпадают, то операция будет использовать объединения индексов:

In [78]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [79]:
series2

b    0
e    1
f    2
dtype: int64

In [80]:
df

b     d     e
U  0.0   1.0   2.0
O  3.0   4.0   5.0
T  6.0   7.0   8.0
Z  9.0  10.0  11.0

In [81]:
df + series2

b   d     e   f
U  0.0 NaN   3.0 NaN
O  3.0 NaN   6.0 NaN
T  6.0 NaN   9.0 NaN
Z  9.0 NaN  12.0 NaN

Если хочется broadcast по столбцам, то нужно использовать один из 4 методов, которые мы поисали ранее:

In [82]:
series3 = df['d']

In [83]:
series3

U     1.0
O     4.0
T     7.0
Z    10.0
Name: d, dtype: float64

In [84]:
df

b     d     e
U  0.0   1.0   2.0
O  3.0   4.0   5.0
T  6.0   7.0   8.0
Z  9.0  10.0  11.0

In [85]:
series3

U     1.0
O     4.0
T     7.0
Z    10.0
Name: d, dtype: float64

In [86]:
df.sub(series3, axis=0)

b    d    e
U -1.0  0.0  1.0
O -1.0  0.0  1.0
T -1.0  0.0  1.0
Z -1.0  0.0  1.0

In [87]:
df.sub?

# 1.2. Индексирование.

Для индекса pandas имеет отдельный тип объекта - index object.

In [88]:
s1 = pd.Series(range(3), index=['a', 'b', 'c'])

In [89]:
s1

a    0
b    1
c    2
dtype: int64

In [90]:
index = s1.index

In [91]:
index

Index(['a', 'b', 'c'], dtype='object')

In [92]:
index[0]

'a'

In [93]:
s2 = pd.Series([1.5, -2.5, 0], index=index)

In [94]:
s2.index is s1.index

True

In [95]:
index

Index(['a', 'b', 'c'], dtype='object')

** Реиндексирование **

In [96]:
ser3 = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [97]:
ser3

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [98]:
ser4 = ser3.reindex(['a', 'b', 'c', 'd', 'e'])

In [99]:
ser4

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

Столь же просто менять индекс объекта DataFrame:

In [100]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'], 
                     columns=['Ohio', 'Texas', 'California'])

In [101]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [102]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])

In [103]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [104]:
states = ['Texas', 'Utah', 'California']

In [105]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [108]:
ser3[ser3 > 0]

d    4.5
b    7.2
c    3.6
dtype: float64

In [109]:
frame.rename(columns={'Texas': "Moscow"})

Ohio  Moscow  California
a     0       1           2
c     3       4           5
d     6       7           8

# 1.3. Работа со столбцами.

In [110]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), 
                  index=['F', 'S', 'T', 'R'])

In [111]:
frame

b         d         e
F -1.059962  1.528572  2.034407
S  1.226435 -0.542333  0.660102
T -0.473043  0.317886 -1.135958
R  0.730341 -0.223223  1.054662

Как вы уже поянли, никаких проблем с функцией, которая работает в numpy поэлементно, у нас не возникнет:

In [112]:
np.power(frame, 2)

b         d         e
F  1.123519  2.336532  4.138814
S  1.504144  0.294125  0.435734
T  0.223770  0.101051  1.290401
R  0.533399  0.049828  1.112313

Однако, чаще нам нужно применить функцию к какому либо столбцу - например, почитать абсолютное значение, сконвертировать из ts в datetime итд.

In [113]:
frame

b         d         e
F -1.059962  1.528572  2.034407
S  1.226435 -0.542333  0.660102
T -0.473043  0.317886 -1.135958
R  0.730341 -0.223223  1.054662

In [114]:
new_format = lambda x: '%.2f' % x

In [115]:
frame.applymap(new_format)

b      d      e
F  -1.06   1.53   2.03
S   1.23  -0.54   0.66
T  -0.47   0.32  -1.14
R   0.73  -0.22   1.05

Для Series метод назывется map().

In [116]:
frame['e'] = frame['e'].map(lambda x: x ** 2) 

In [117]:
frame['e'] = frame['e'] ** 2

In [118]:
frame['e'] = frame['e'].apply(lambda x: x ** 2) 

Чтобы получить доступ к списку названий, достаточно обратиться к df.columns:

In [119]:
frame.columns

Index(['b', 'd', 'e'], dtype='object')

Также полезно следующее:

In [120]:
df.dtypes

b    float64
d    float64
e    float64
dtype: object

Для сортировки по индексу стоит вызвать df.sort_index(), который возвращает копию исходного объекта:

In [123]:
frame

b         d           e
F -1.059962  1.528572  293.429348
S  1.226435 -0.542333    0.036049
T -0.473043  0.317886    2.772675
R  0.730341 -0.223223    1.530763

In [124]:
frame.sort_index()

b         d           e
F -1.059962  1.528572  293.429348
R  0.730341 -0.223223    1.530763
S  1.226435 -0.542333    0.036049
T -0.473043  0.317886    2.772675

In [125]:
frame.sort_index(axis=1, ascending=False)

e         d         b
F  293.429348  1.528572 -1.059962
S    0.036049 -0.542333  1.226435
T    2.772675  0.317886 -0.473043
R    1.530763 -0.223223  0.730341

Чтобы отсортировать по значению столбцов:

In [126]:
frame.sort_index(by=['d', 'b'])

TypeError: sort_index() got an unexpected keyword argument 'by'

In [ ]:
frame.sort_values(by=['d', 'b'])

Также значениям можно присвоить ранг:

In [ ]:
frame.info()

In [ ]:
frame.describe()

# 1.4. File I/O.

http://pandas.pydata.org/pandas-docs/stable/io.html

Как видно из оффициальной документации (выше), в качестве входного формата могут использоваться следующие:
* read_csv
* read_excel
* read_hdf
* read_sql
* read_json
* read_msgpack (experimental)
* read_html
* read_gbq (experimental)
* read_stata
* read_sas
* read_clipboard
* read_pickle

Каждый из них снабжен "зеркальным" методом "to".

Думаю, что чаще всего вас придется пользоваться методом "read_csv". Подробная сигнатура:

In [ ]:
pd.read_csv?

In [ ]:
frame.to_csv("frame.csv.gz", sep="\t", encoding="utf-8", compression="gzip")

In [ ]:
!ls

In [ ]:
!zcat frame.csv.gz

In [ ]:
frame.head(1)

In [ ]:
frame.columns

In [ ]:
frame

In [ ]:
frame.get_dtype_counts()

In [ ]:
frame["b"].value_counts()

In [ ]:
frame.values